version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reportdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=feedback_report.settings

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A feedback_report worker --loglevel=info
    depends_on:
      - redis
      - db
    networks:
      - app-network

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BROKER=redis://redis:6379/0
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge